name: Rust CI
on:
  push:
    branches: [main]
  merge_group:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  cargo-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@nextest
      - name: cargo test
        run: cargo nextest run --release --all --all-features --locked
  cargo-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        target: ["native", "cannon", "asterisc"]
    name: lint-${{ matrix.target }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
      - uses: taiki-e/install-action@just
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          prefix-key: ${{ matrix.target }}
      - name: fmt + lint
        run: just lint-${{ matrix.target }}
  cargo-build-benches:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    name: build-benchmarks
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
      - uses: taiki-e/install-action@just
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: build benches
        run: cargo bench --no-run --workspace --all --features test-utils
  cargo-build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        target: ["native", "cannon", "asterisc"]
    name: build-${{ matrix.target }}
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
      - uses: taiki-e/install-action@just
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          prefix-key: ${{ matrix.target }}
      - name: build
        run: just build-${{ matrix.target }}
